-- Clubhouse roster seed (AUTH-5): names-only claim picker.
-- Derived 2026-08-08 from the engine's pair_history (373 rows, 6 session
-- dates, Feb 19 - Mar 4 2026). Test data excluded: every NATO-alphabet name
-- (Alpha1-6, Bravo*, Charlie*, ... , LateCee*) appeared ONLY on the
-- 2026-03-01 simulation day. Case/annotation variants folded ("kayode (C)",
-- "Ossai (not paid)", "martin's"). Lookalike spellings that CO-OCCURRED on
-- the same session date are different people and stay separate:
--   Ade+Adee, Debbie+Deborah, Temi+Temitope, Timi+"Timi Olaoye",
--   Tomi+Tumu/Tolu, Ife+Ifeoma, Donell+Donnel.
-- Idempotent: safe to re-run. Fix a name later with a plain UPDATE.
insert into clubhouse_roster (player_id, display_name) values
('p-abubakar','Abubakar'),
('p-ade','Ade'),
('p-adee','Adee'),
('p-akin','Akin'),
('p-albright','Albright'),
('p-alex','Alex'),
('p-amadiosi','Amadiosi'),
('p-amber','Amber'),
('p-andrew','Andrew'),
('p-ayo','Ayo'),
('p-benita','Benita'),
('p-benson','Benson'),
('p-brian','Brian'),
('p-carlos','Carlos'),
('p-chibuike','Chibuike'),
('p-chizea','Chizea'),
('p-david','David'),
('p-debbie','Debbie'),
('p-deborah','Deborah'),
('p-diana','Diana'),
('p-donell','Donell'),
('p-donnel','Donnel'),
('p-donnell','Donnell'),
('p-doris','Doris'),
('p-duke','Duke'),
('p-dynamite','Dynamite'),
('p-edmund','Edmund'),
('p-elvis','Elvis'),
('p-eman','Eman'),
('p-emmanuel','Emmanuel'),
('p-ese','Ese'),
('p-eve','Eve'),
('p-fiyin','Fiyin'),
('p-folarin','Folarin'),
('p-frank','Frank'),
('p-grace','Grace'),
('p-hamid','Hamid'),
('p-hank','Hank'),
('p-ife','Ife'),
('p-ifeoma','Ifeoma'),
('p-ig','IG'),
('p-jaidan','Jaidan'),
('p-jen','Jen'),
('p-kayode','Kayode'),
('p-kelechi','Kelechi'),
('p-kenisha','Kenisha'),
('p-malik','Malik'),
('p-martins','Martins'),
('p-ore','Ore'),
('p-ossai','Ossai'),
('p-paola','Paola'),
('p-rob','Rob'),
('p-sam','Sam'),
('p-samuel','Samuel'),
('p-shana','Shana'),
('p-tamilore','Tamilore'),
('p-temi','Temi'),
('p-temitope','Temitope'),
('p-timi','Timi'),
('p-timi-olaoye','Timi Olaoye'),
('p-tofunmi','Tofunmi'),
('p-tolu','Tolu'),
('p-tomi','Tomi'),
('p-tumi','Tumi'),
('p-tyrell','Tyrell'),
('p-valerie','Valerie')
on conflict (player_id) do update
  set display_name = excluded.display_name, updated_at = now();

select count(*) as roster_size from clubhouse_roster;
