-- Clubhouse migration 005: attendance, and the roster policy that was too wide.
--
-- APPLY: paste into the Supabase SQL editor (project flahcijysipymafazhxq).
-- Idempotent: safe to re-run.
--
-- REQUIRES is_engine_admin(), created in
-- supabase/migrations/20260814_engine_admins.sql. Two migration folders is
-- the state of the world here: the engine's live under supabase/, the
-- clubhouse's under src/clubhouse/. One database, two series.
--
-- ROLLBACK (in this order):
--   drop function if exists mark_attendance_no_show(text, text);
--   drop table    if exists clubhouse_attendance;          -- takes its trigger
--   drop function if exists clubhouse_attendance_guard();
--   drop policy   if exists "roster read for authenticated" on clubhouse_roster;
--   create policy "roster read for authenticated"
--     on clubhouse_roster for select to authenticated using (true);
--
-- ---------------------------------------------------------------------------
-- WHY THIS TABLE EXISTS
--
-- "Nights attended" is currently derived from clubhouse_pairs: you counted
-- as present on a night only if you were paired AND that night was
-- published. Someone who turned up, sat out, and went home never happened.
-- This table is the record of who was in the room, independent of whether
-- they played a scored game.
--
-- It is keyed off clubhouse_roster, which is already the person table. No
-- new person table, by instruction and by preference.
-- ---------------------------------------------------------------------------

create table if not exists clubhouse_attendance (
  -- NOT a foreign key to clubhouse_sessions, deliberately. That table is the
  -- PUBLISHED record: inserting a row there makes a night appear in the
  -- room. Attendance has to be writable BEFORE a night is published — the
  -- courtside check-in, the Sunday tap-off — so an FK would force us to
  -- publish an empty session just to record that someone walked in. The
  -- session_id is generated by one code path and matched by convention.
  session_id    text not null,

  -- The FK the schema map said was missing everywhere (C3). Attendance is
  -- the first table that cannot orphan. RESTRICT, not CASCADE: deleting a
  -- roster row must not silently delete the record of nights they attended.
  player_id     text not null references clubhouse_roster (player_id) on delete restrict,

  status        text not null default 'booked',

  -- How the row came to exist. Set once at insert and never rewritten (see
  -- the guard): a booked row that later shows up still says 'booking',
  -- which is the useful fact — they booked, and they came.
  source        text not null,

  -- Null when nobody recorded a time. Publish knows you were there but not
  -- when, and inventing a time is inventing an operational fact.
  checked_in_at timestamptz,

  -- Who last wrote this row, paired with updated_at.
  recorded_by   uuid references auth.users (id),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- "One row per person per session."
  primary key (session_id, player_id),

  constraint attendance_status check (status in ('present', 'booked', 'no_show')),
  constraint attendance_source check (source in ('publish', 'checkin', 'walkin', 'booking'))
);

create index if not exists clubhouse_attendance_player
  on clubhouse_attendance (player_id);

-- ---------------------------------------------------------------------------
-- THE GUARD: idempotency and one-directional status.
--
-- The unique key stops a second Publish creating a duplicate row. It does
-- NOT stop a second Publish overwriting the row with worse information, and
-- that is the failure that matters:
--
--   19:58  check-in     -> present, checked_in_at 19:58
--   22:30  publish      -> present, checked_in_at null   (publish knows no time)
--   22:31  publish again-> present                        (a mis-tap, or a retry)
--
-- Without this trigger, step 2 erases a real check-in time and step 3 is
-- indistinguishable from step 2. With it, a re-run is a no-op on everything
-- that already holds better information.
--
-- Transitions, deliberately asymmetric:
--   booked  -> present   yes. They showed up.
--   booked  -> no_show   yes. This is the Step 4 close-the-night sweep.
--   no_show -> present   yes. An admin correcting a wrong sweep.
--   present -> booked    NEVER. Presence is not un-observed.
--   no_show -> booked    NEVER. Same reason, one step down.
--   present -> no_show   only through mark_attendance_no_show() below.
--
-- That last line is the whole point. Step 4's sweep flips leftover booked
-- rows to no_show. If a mis-timed sweep could touch present rows, one run
-- rewrites a night's attendance into an accusation. The sweep is a plain
-- UPDATE and cannot set the override, so the database refuses it — this
-- does not depend on the sweep's WHERE clause being written correctly.
--
-- Honest about its limits: the override guards against automation, not
-- against a determined admin. An admin can always call the function.
-- ---------------------------------------------------------------------------

create or replace function clubhouse_attendance_guard()
returns trigger
language plpgsql
as $$
begin
  -- The earliest known check-in wins. LEAST ignores nulls, so a later write
  -- can FILL a null but can never move a real time forward.
  new.checked_in_at := least(old.checked_in_at, new.checked_in_at);

  -- Origin facts. Silently preserved rather than rejected, on purpose: the
  -- publish upsert passes source='publish' for every row, and it should be a
  -- no-op on the ones that came from a check-in, not an error.
  new.source     := old.source;
  new.created_at := old.created_at;

  if old.status = 'present' and new.status <> 'present' then
    if new.status = 'no_show'
       and coalesce(current_setting('clubpto.attendance_override', true), '') = 'on' then
      null; -- explicit admin correction
    else
      raise exception using
        errcode = 'check_violation',
        message = format('attendance: %s -> %s is not allowed', old.status, new.status),
        detail  = format('session %s, player %s', old.session_id, old.player_id),
        hint    = 'A present row only changes through mark_attendance_no_show().';
    end if;
  end if;

  if old.status = 'no_show' and new.status = 'booked' then
    raise exception using
      errcode = 'check_violation',
      message = 'attendance: no_show -> booked is not allowed',
      detail  = format('session %s, player %s', old.session_id, old.player_id),
      hint    = 'Correct a wrong no_show by marking them present.';
  end if;

  new.updated_at := now();
  return new;
end
$$;

drop trigger if exists clubhouse_attendance_guard_trg on clubhouse_attendance;
create trigger clubhouse_attendance_guard_trg
  before update on clubhouse_attendance
  for each row execute function clubhouse_attendance_guard();

-- The ONLY route from present to no_show. security invoker, so the
-- admin-only update policy still applies — this function grants no
-- authority the caller does not already have. It exists to make the
-- downgrade a deliberate, named act rather than a side effect of a sweep.
create or replace function mark_attendance_no_show(p_session_id text, p_player_id text)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  -- true = transaction-local. PostgREST wraps each request in its own
  -- transaction, so the override cannot outlive this call.
  perform set_config('clubpto.attendance_override', 'on', true);
  update clubhouse_attendance
     set status = 'no_show', recorded_by = auth.uid()
   where session_id = p_session_id and player_id = p_player_id;
  perform set_config('clubpto.attendance_override', 'off', true);
end
$$;

-- ---------------------------------------------------------------------------
-- RLS. Written in the same migration as the table, not after.
-- ---------------------------------------------------------------------------

alter table clubhouse_attendance enable row level security;

-- Read: your own rows, or an admin's full view. NOT `to authenticated`
-- alone — every one of the 66 roster members holds a passwordless login on
-- this project, and attendance is a record of who was where on which night.
-- The clubhouse_links sub-select is itself under RLS ("own link read"), so
-- it can only ever return the caller's own link.
drop policy if exists "attendance self read" on clubhouse_attendance;
create policy "attendance self read"
  on clubhouse_attendance for select to authenticated
  using (
    is_engine_admin()
    or player_id in (
      select l.player_id from clubhouse_links l
      where l.auth_user_id = auth.uid() and not l.revoked
    )
  );

-- Writes are admin-only. A member cannot mark themselves present.
drop policy if exists "attendance admin insert" on clubhouse_attendance;
create policy "attendance admin insert"
  on clubhouse_attendance for insert to authenticated
  with check (is_engine_admin());

drop policy if exists "attendance admin update" on clubhouse_attendance;
create policy "attendance admin update"
  on clubhouse_attendance for update to authenticated
  using (is_engine_admin()) with check (is_engine_admin());

-- Delete IS allowed, admin-only, unlike game_state_archive. Attendance is a
-- live working record edited courtside, and the realistic error is tapping
-- the wrong name. Blocking delete would leave a permanent wrong row
-- inflating someone's nights-out count with no way to fix it from the app.
-- Marking them no_show instead would be a different lie.
drop policy if exists "attendance admin delete" on clubhouse_attendance;
create policy "attendance admin delete"
  on clubhouse_attendance for delete to authenticated
  using (is_engine_admin());

-- Nothing for anon. The publishable key in the browser bundle sees nothing.

-- ---------------------------------------------------------------------------
-- THE ROSTER POLICY WAS TOO WIDE.
--
-- Was: SELECT to authenticated USING (true) — every signed-in member could
-- read every roster row, hidden ones included. Migration 004 added the
-- hidden flag for PROF-3 ("a hidden player must vanish from every surface")
-- and then enforced it only in the browser, with .eq("hidden", false) in
-- fetchRoster(). A filter in the client is not a policy.
--
-- The half that breaks silently is the other direction. Narrow this to
-- `hidden = false` alone and a hidden player loses sight of their OWN row:
-- getMyIdentity() reads it for the greeting, and the seat falls back to
-- "Club member". Hiding from the room must not hide you from yourself.
--
-- Known consequence, accepted: a player who is hidden AND has not claimed
-- their name cannot see it in the claim picker, because before the claim
-- there is no ownership to test. Zero rows are hidden today. The fix if it
-- ever happens is to unhide, let them claim, hide again.
-- ---------------------------------------------------------------------------

drop policy if exists "roster read for authenticated" on clubhouse_roster;
create policy "roster read for authenticated"
  on clubhouse_roster for select to authenticated
  using (
    hidden = false
    or player_id in (
      select l.player_id from clubhouse_links l
      where l.auth_user_id = auth.uid() and not l.revoked
    )
  );

-- The other seven content tables are left exactly as they are. They hold
-- what the room is for — sessions, pairs, results, champions, finalists,
-- totals, rivalries — and member-visible is the intent there.
