// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-upcoming-sessions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_sessions_default = defineTool({
  name: "list_upcoming_sessions",
  title: "List upcoming sessions",
  description: "List active upcoming Club PTO padel sessions with date, time, price, and spots remaining.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max sessions to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await client(ctx).from("sessions").select("id, session_date, session_time, price_cents, spots_remaining, max_spots, is_active").eq("is_active", true).gte("session_date", today).order("session_date", { ascending: true }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-players.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_players_default = defineTool2({
  name: "list_players",
  title: "List players",
  description: "List players in the Club PTO roster with name, tier, VIP flag, and cumulative stats.",
  inputSchema: {
    tier: z2.enum(["A", "B", "C"]).optional().describe("Filter by tier."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max players (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tier, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client2(ctx).from("players").select("id, name, tier, is_vip, total_points, total_wins").order("total_points", { ascending: false }).limit(limit ?? 50);
    if (tier) q = q.eq("tier", tier);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { players: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_leaderboard_default = defineTool3({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Get the top Club PTO players ranked by total points across all sessions.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Top N (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client3(ctx).from("players").select("name, tier, total_points, total_wins").order("total_points", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ranked = (data ?? []).map((p, i) => ({ rank: i + 1, ...p }));
    return {
      content: [{ type: "text", text: JSON.stringify(ranked, null, 2) }],
      structuredContent: { leaderboard: ranked }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ikfbtktofcfkpqxwlfku";
var mcp_default = defineMcp({
  name: "club-pto-mcp",
  title: "Club PTO",
  version: "0.1.0",
  instructions: "Tools for Club PTO \u2014 a Toronto padel league. Use list_upcoming_sessions for booking info, list_players for the roster, and get_leaderboard for top players.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_upcoming_sessions_default, list_players_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
